=== Bloodymary786/ivy_training/ivytrainingcode/ws1/xmldemo/employees.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" 
	targetNamespace="http://www.ivy.com/employees" 
	xmlns:tns="http://www.ivy.com/employees" elementFormDefault="unqualified">

    <element name="employees" type="tns:employeesType"></element>
    
    <complexType name="employeesType">
    	<sequence>
    		<element name="companyName" type="string" maxOccurs="1"
    			minOccurs="1">
    		</element>
    		<element name="employee" type="tns:employeeType" maxOccurs="unbounded" minOccurs="1"></element>
    	</sequence>
    </complexType>

    <complexType name="employeeType">
    	<sequence>
    		<element name="id" type="int"></element>
    		<element name="name" type="string"></element>
    		<element name="address" type="string"></element>
    		<element name="dob" type="date"></element>
    	</sequence>
    </complexType>
</schema>

=== Bloodymary786/ivy_training/ivytrainingcode/ws1/xmldemo2/employees.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:employees xmlns:tns="http://www.ivy.com/employees" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.ivy.com/employees employees.xsd ">
  <companyName>ivy</companyName>
  <employee>
    <id>1</id>
    <name>name</name>
    <address>address</address>
    <dob>2001-01-01</dob>
  </employee>
   <employee>
    <id>3</id>
    <name>name</name>
    <address>address</address>
    <dob>2001-01-01</dob>
  </employee>
</tns:employees>
